name: Bug report
description: Create a report to help me improve RedirectTube!
title: '[Bug]: '
labels:
  - bug
assignees:
  - MStankiewiczOfficial
body:
  - type: markdown
    attributes:
      value: Accepted are answers in `English`, `Polish`.
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: To Reproduce
      description: Steps to reproduce the behavior
      placeholder: 1. Go to '...' 2. Click on '....' 3. Scroll down to '....' 4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      description: Choose on which platform the bug occurs.
      multiple: true
      options:
        - Linux
        - macOS
        - Windows
    validations:
      required: true
  - type: input
    id: browser-version
    attributes:
      label: Firefox version
      description: To check, go to [about:support](about:support).
      placeholder: 128.5.2esr
    validations:
      required: true
  - type: input
    id: app-version
    attributes:
      label: FreeTube version
      description: To check, go to "About" section.
      placeholder: 0.22.1 Beta
    validations:
      required: true
  - type: input
    id: extension-version
    attributes:
      label: RedirectTube version
      description: To check, go to [about:addons](about:addons) and click extension name.
      placeholder: 1.0.0
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: Additional context
      description: Add any other context about the problem here.
  - type: checkboxes
    id: statements
    attributes:
      label: Statements
      options:
        - label: I use the latest version of RedirectTube.
          required: true
        - label: I use the latest version of Mozilla Firefox.
          required: true
        - label: I verified that the error has not already been reported on GitHub.
          required: true